export const ANIMATION_KEYS = {
  HEADER_FADE_IN_DOWN: 'HEADER_FADE_IN_DOWN',
  BANNER_TITLE_SLIDE_IN: 'BANNER_TITLE_SLIDE_IN',
  TAGLINE_REVEAL_CONTENT: 'TAGLINE_REVEAL_CONTENT',
  FEATURED_REVEAL_CONTENT: 'FEATURED_REVEAL_CONTENT',
  FEATURED_METADATA_REVEAL_CONTENT: 'FEATURED_METADATA_REVEAL_CONTENT',
  FEATURED_ENLARGE_ARROW: 'FEATURED_ENLARGE_ARROW',
  CONTACT_REVEAL_CONTENT: 'CONTACT_REVEAL_CONTENT',
  MENU_SLIDE_IN: 'MENU_SLIDE_IN',
  MENU_ARROW_SLIDE_IN: 'MENU_ARROW_SLIDE_IN',
  MENU_MEDIA_SLIDE_IN: 'MENU_MEDIA_SLIDE_IN',
  MENU_MEDIA_SLIDE_OUT: 'MENU_MEDIA_SLIDE_OUT'
}
